name: Setup python and scons
description: Setup python, install the pip version of scons.
inputs:
  python-version:
    description: The python version to use.
    default: 3.x
  python-arch:
    description: The python architecture.
    default: x64
  shell:
    description: the shell to run this under
    default: sh
runs:
  using: composite
  steps:
  - name: Set up Python 3.x
    uses: actions/setup-python@v2
    with:
      python-version: ${{ inputs.python-version }}
      architecture: ${{ inputs.python-arch }}
  - name: Setup scons
    shell: ${{ inputs.shell }}
    run: |
      python -c "import sys; print(sys.version)"
      python -m pip install scons
      scons --version
