name: 🍏 iOS Builds
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

# Global Settings
env:
  SCONSFLAGS: warnings=extra werror=yes debug_symbols=no module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-ios
  cancel-in-progress: true

jobs:
  ios-template:
    runs-on: "macos-latest"
    name: Template (target=template_release)

    steps:
      - name: Checkout Godot
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: ${{ inputs.version }}

      - name: Checkout ECMAScript
        uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}/modules/javascript/

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: ios
          target: template_release
          tests: false

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
