name: "\U0001F34E macOS Builds"
true:
- push
- pull_request
env:
  GODOT_BASE_BRANCH: 3.4-stable
  SCONSFLAG: ''
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no
concurrency:
  cancel-in-progress: true
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
jobs:
  build-macos:
    name: ${{ matrix.name }}
    runs-on: macos-latest
    steps:
    - name: Checkout Godot
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GODOT_BASE_BRANCH }}
        repository: godotengine/godot
    - name: Checkout ECMSAScript
      uses: actions/checkout@v2
      with:
        path: ${{github.workspace}}/modules/ECMAScript/
    - continue-on-error: true
      name: Setup Godot build cache
      uses: ./.github/actions/godot-cache
      with:
        cache-name: ${{ matrix.cache-name }}
    - name: Setup python and scons
      uses: ./.github/actions/godot-deps
    - name: Compilation
      uses: ./.github/actions/godot-build
      with:
        platform: osx
        sconsflags: ${{ env.SCONSFLAGS }}
        target: ${{ matrix.target }}
        tools: ${{ matrix.tools }}
    - name: Upload artifact
      uses: ./.github/actions/upload-artifact
      with:
        name: ${{ matrix.cache-name }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - bin: ./bin/godot.osx.opt.tools.64
          cache-name: macos-editor
          name: Editor (target=release_debug, tools=yes)
          target: release_debug
          tools: true
        - cache-name: macos-template
          name: Template (target=release, tools=no)
          target: release
          tools: false
