name: 🚢 Publish release
'on':
  workflow_run:
    workflows:
    - 🌐 JavaScript Builds
    types:
    - completed
jobs:
  collect-template:
    runs-on: ubuntu-latest
    steps:
    - name: download artifacts
      uses: actions/github-script@v6
      with:
        script: |-
          var all_workflows = await github.rest.actions.listWorkflowRunsForRepo({
             owner: context.repo.owner,
             repo: context.repo.repo,
          });
          console.log("my sha " + "${{ github.sha }}" + " out of " + all_workflows.data.workflow_runs.length );
          for (const workflow of all_workflows.data.workflow_runs) {
              if (workflow.HeadSha == "${{ github.sha }}") {
                  console.log("found one " + workflow.ID);
                  var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                         owner: context.repo.owner,
                         repo: context.repo.repo,
                         run_id: workflow.ID,
                         per_page: 100,
                  });
                  for (const artifact of artifacts.data.artifacts) {
                      console.log("found one artifact " + artifact.id + " " + artifact.name);
                      var download = await github.rest.actions.downloadArtifact({
                         owner: context.repo.owner,
                         repo: context.repo.repo,
                         artifact_id: artifact.id,
                         archive_format: 'zip',
                      });
                      var fs = require('fs');
                      fs.writeFileSync('${{github.workspace}}/' + artifact.name + '.zip', Buffer.from(download.data));
                  }
              }
          }
    - name: show dir
      run: ls -R && echo bob && ls */
