name: 🚢 Publish release
'on':
  workflow_run:
    workflows:
    - 🤖 Android Builds
    - 🍏 iOS Builds
    - 🌐 JavaScript Builds
    - 🐧 Linux Builds
    - 🍎 macOS Builds
    - ☁ Server Builds
    - 🏁 Windows Builds
    types:
    - completed
jobs:
  collect-template:
    runs-on: ubuntu-latest
    steps:
    - name: wait 10 min
      run: sleep 900
    - name: download artifacts
      uses: actions/download-artifact@v3
    - name: show dir
      run: ls -R && echo bob && ls */
