name: 🚢 Publish release
'on':
  workflow_run:
    workflows:
    - 🌐 JavaScript Builds
    types:
    - completed
jobs:
  collect-template:
    runs-on: ubuntu-latest
    steps:
    - name: download artifacts
      uses: actions/github-script@v6
      with:
        script: "var total_slept = 0;\nvar downloaded_files = [];\nvar seen_completed_wfs\
          \ = [];\nvar expected_to_see = 7;\nwhile (total_slept < 3600000 && seen_completed_wfs.length\
          \ < expected_to_see) {\n\tvar all_workflows = await github.rest.actions.listWorkflowRunsForRepo({\n\
          \t\towner: context.repo.owner,\n\t\trepo: context.repo.repo,\n\t});\n\t\
          console.log(\"expecting \" + expected_to_see + \" more files but at \" +\
          \ downloaded_files.length + \" with \" + downloaded_files);\n\tfor (const\
          \ workflow of all_workflows.data.workflow_runs) {\n\t\tif (workflow.head_sha\
          \ == \"${{ github.sha }}\") {\n\t\t\tconsole.log(\"found \" + workflow.name\
          \ + \" \" + workflow.status);\n\t\t\tif (workflow.status == \"completed\"\
          ) {\n\t\t\t\tif (seen_completed_wfs.includes(workflow.name)) {continue;}\n\
          \t\t\t\tif (workflow.conclusion == \"success\") {\n\t\t\t\t\tvar artifacts\
          \ = await github.rest.actions.listWorkflowRunArtifacts({\n\t\t\t\t\t\towner:\
          \ context.repo.owner,\n\t\t\t\t\t\trepo: context.repo.repo,\n\t\t\t\t\t\t\
          run_id: workflow.id,\n\t\t\t\t\t\tper_page: 100,\n\t\t\t\t\t});\n\t\t\t\t\
          \tfor (const artifact of artifacts.data.artifacts) {\n\t\t\t\t\t\tvar fn\
          \ = '${{github.workspace}}/' + artifact.name + '.zip';\n\t\t\t\t\t\tif (downloaded_files.includes(fn))\
          \ {continue;}\n\t\t\t\t\t\tvar download = await github.rest.actions.downloadArtifact({\n\
          \t\t\t\t\t\t\towner: context.repo.owner,\n\t\t\t\t\t\t\trepo: context.repo.repo,\n\
          \t\t\t\t\t\t\tartifact_id: artifact.id,\n\t\t\t\t\t\t\tarchive_format: 'zip',\n\
          \t\t\t\t\t\t});\n\t\t\t\t\t\tvar fs = require('fs');\n\t\t\t\t\t\tfs.writeFileSync(fn,\
          \ Buffer.from(download.data));\n\t\t\t\t\t\tdownloaded_files.push(fn);\n\
          \t\t\t\t\t}\n\t\t\t\t\tseen_completed_wfs.push(workflow.name);\n\t\t\t\t\
          }\n\t\t\t}\n\t\t}\n\t}\n\tif (seen_completed_wfs.length < expected_to_see)\
          \ {\n\t\tconsole.log(\"sleeping \" + 300000);\n\t\tawait new Promise(r =>\
          \ setTimeout(r, 300000));\n\t\ttotal_slept = total_slept + 300000;\n\t\t\
          console.log(\"done sleeping \" + 300000);\n\t}\n}\nconsole.log(downloaded_files);"
    - name: show dir
      run: ls -R && echo bob && unzip '*.zip' && ls -R
