name: 📊 Static Checks
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-static
  cancel-in-progress: true

jobs:
  static-checks:
    name: Code style, file formatting, and docs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Godot
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: ${{ inputs.version }}
          sparse-checkout: |
            misc/scripts
          sparse-checkout-cone-mode: false
          path: tmp

      - name: Checkout workaround
        run: |
          mv tmp/misc/scripts misc/scripts
          cp clang_format.sh misc/scripts/clang_format.sh

      - name: Install APT dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: dos2unix libxml2-utils moreutils

      - name: Install Python dependencies and general setup
        run: |
          pip3 install black==22.3.0 pytest==7.1.2 mypy==0.971
          git config diff.wsErrorHighlight all

      - name: Get changed files
        id: changed-files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            files=$(gh pr diff ${{ github.event.pull_request.number }} --name-only)
          elif [ "${{ github.event_name }}" == "push" -a "${{ github.event.forced }}" == "false" -a "${{ github.event.created }}" == "false" ]; then
            files=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }}..${{ github.event.after }} 2> /dev/null || true)
          fi
          echo "$files" >> changed.txt
          cat changed.txt
          files=$(echo "$files" | grep -v 'thirdparty' | xargs -I {} sh -c 'echo "./{}"' | tr '\n' ' ')
          echo "CHANGED_FILES=$files" >> $GITHUB_ENV

      - name: File formatting checks (file_format.sh)
        run: |
          bash ./misc/scripts/file_format.sh changed.txt

      - name: Python scripts static analysis (mypy_check.sh)
        run: |
          if grep -qE '\.py$|SConstruct|SCsub' changed.txt || [ -z "$(cat changed.txt)" ]; then
            bash ./misc/scripts/mypy_check.sh
          else
            echo "Skipping Python static analysis as no Python files were changed."
          fi

      - name: Style checks via clang-format (clang_format.sh)
        run: |
          clang-format --version
          bash ./misc/scripts/clang_format.sh changed.txt
