name: 🌐 Web Builds
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string


# Global Settings
env:
  SCONSFLAGS: warnings=extra werror=yes debug_symbols=no
  EM_VERSION: 3.1.18
  EM_CACHE_FOLDER: "emsdk-cache"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-web
  cancel-in-progress: true

jobs:
  web-template:
    runs-on: "ubuntu-20.04"
    name: Template (target=template_release)

    steps:
      - name: Checkout Godot
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: ${{ inputs.version }}

      - name: Checkout ECMAScript
        uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}/modules/javascript/

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: web
          target: template_release
          tests: false

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
